galaxy_info:
  author: ALTO HOLZ
  description: Terrassenplaner – Rolle container
  license: proprietary
  min_ansible_version: "2.17"
  platforms:
    - name: Debian
      versions: [trixie]
dependencies:
  - role: planer
