// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/datenhaltung/entitaeten.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4199694471024936157),
    name: 'Aenderung',
    lastPropertyId: const obx_int.IdUid(9, 8573095070367006885),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2137812312726579873),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8930244852648199785),
        name: 'schluessel',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8905860940179439852),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1210037017693473005),
        name: 'knoten',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8021987696294641833),
        name: 'seq',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 2986106118830378154),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7035142836940928740),
        name: 'entitaet',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8556489672261359609),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7016671356637213546),
        name: 'partition',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 36167693237574578),
        name: 'hlc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8573095070367006885),
        name: 'art',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5391721831752821817),
    name: 'Benutzer',
    lastPropertyId: const obx_int.IdUid(13, 1673270093877694242),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7330662995083646838),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5828384574916831161),
        name: 'uid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 7911314867250049373),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 704594392608506628),
        name: 'partition',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1380542247077630684),
        name: 'hlc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5513814915088336588),
        name: 'knoten',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4998498917849275631),
        name: 'geloeschtAm',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 286666604384982042),
        name: 'schema',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5012885621349221597),
        name: 'authId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 6839961270107171854),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 692959789547615818),
        name: 'salt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2714607709921550981),
        name: 'iterationen',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1409256566524356484),
        name: 'storedKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 28706912317421964),
        name: 'serverKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1673270093877694242),
        name: 'rolle',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5391721831752821817),
    lastIndexId: const obx_int.IdUid(4, 6839961270107171854),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Aenderung: obx_int.EntityDefinition<Aenderung>(
      model: _entities[0],
      toOneRelations: (Aenderung object) => [],
      toManyRelations: (Aenderung object) => {},
      getId: (Aenderung object) => object.id,
      setId: (Aenderung object, int id) {
        object.id = id;
      },
      objectToFB: (Aenderung object, fb.Builder fbb) {
        final schluesselOffset = fbb.writeString(object.schluessel);
        final knotenOffset = fbb.writeString(object.knoten);
        final entitaetOffset = fbb.writeString(object.entitaet);
        final uidOffset = fbb.writeString(object.uid);
        final partitionOffset = fbb.writeString(object.partition);
        final hlcOffset = fbb.writeString(object.hlc);
        final artOffset = fbb.writeString(object.art);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, schluesselOffset);
        fbb.addOffset(2, knotenOffset);
        fbb.addInt64(3, object.seq);
        fbb.addOffset(4, entitaetOffset);
        fbb.addOffset(5, uidOffset);
        fbb.addOffset(6, partitionOffset);
        fbb.addOffset(7, hlcOffset);
        fbb.addOffset(8, artOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final knotenParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 8, '');
        final seqParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final entitaetParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 12, '');
        final uidParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 14, '');
        final partitionParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 16, '');
        final hlcParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 18, '');
        final artParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 20, '');
        final object =
            Aenderung(
                knoten: knotenParam,
                seq: seqParam,
                entitaet: entitaetParam,
                uid: uidParam,
                partition: partitionParam,
                hlc: hlcParam,
                art: artParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..schluessel = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');

        return object;
      },
    ),
    Benutzer: obx_int.EntityDefinition<Benutzer>(
      model: _entities[1],
      toOneRelations: (Benutzer object) => [],
      toManyRelations: (Benutzer object) => {},
      getId: (Benutzer object) => object.id,
      setId: (Benutzer object, int id) {
        object.id = id;
      },
      objectToFB: (Benutzer object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final partitionOffset = fbb.writeString(object.partition);
        final hlcOffset = fbb.writeString(object.hlc);
        final knotenOffset = fbb.writeString(object.knoten);
        final authIdOffset = fbb.writeString(object.authId);
        final saltOffset = fbb.writeString(object.salt);
        final storedKeyOffset = fbb.writeString(object.storedKey);
        final serverKeyOffset = fbb.writeString(object.serverKey);
        final rolleOffset = fbb.writeString(object.rolle);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, partitionOffset);
        fbb.addOffset(3, hlcOffset);
        fbb.addOffset(4, knotenOffset);
        fbb.addInt64(5, object.geloeschtAm);
        fbb.addInt64(6, object.schema);
        fbb.addOffset(7, authIdOffset);
        fbb.addOffset(8, saltOffset);
        fbb.addInt64(9, object.iterationen);
        fbb.addOffset(10, storedKeyOffset);
        fbb.addOffset(11, serverKeyOffset);
        fbb.addOffset(12, rolleOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final authIdParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 18, '');
        final saltParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 20, '');
        final iterationenParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final storedKeyParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 24, '');
        final serverKeyParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 26, '');
        final rolleParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 28, '');
        final object =
            Benutzer(
                authId: authIdParam,
                salt: saltParam,
                iterationen: iterationenParam,
                storedKey: storedKeyParam,
                serverKey: serverKeyParam,
                rolle: rolleParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..uid = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '')
              ..partition = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '')
              ..hlc = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '')
              ..knoten = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '')
              ..geloeschtAm = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                14,
              )
              ..schema = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                16,
                0,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Aenderung] entity fields to define ObjectBox queries.
class Aenderung_ {
  /// See [Aenderung.id].
  static final id = obx.QueryIntegerProperty<Aenderung>(
    _entities[0].properties[0],
  );

  /// See [Aenderung.schluessel].
  static final schluessel = obx.QueryStringProperty<Aenderung>(
    _entities[0].properties[1],
  );

  /// See [Aenderung.knoten].
  static final knoten = obx.QueryStringProperty<Aenderung>(
    _entities[0].properties[2],
  );

  /// See [Aenderung.seq].
  static final seq = obx.QueryIntegerProperty<Aenderung>(
    _entities[0].properties[3],
  );

  /// See [Aenderung.entitaet].
  static final entitaet = obx.QueryStringProperty<Aenderung>(
    _entities[0].properties[4],
  );

  /// See [Aenderung.uid].
  static final uid = obx.QueryStringProperty<Aenderung>(
    _entities[0].properties[5],
  );

  /// See [Aenderung.partition].
  static final partition = obx.QueryStringProperty<Aenderung>(
    _entities[0].properties[6],
  );

  /// See [Aenderung.hlc].
  static final hlc = obx.QueryStringProperty<Aenderung>(
    _entities[0].properties[7],
  );

  /// See [Aenderung.art].
  static final art = obx.QueryStringProperty<Aenderung>(
    _entities[0].properties[8],
  );
}

/// [Benutzer] entity fields to define ObjectBox queries.
class Benutzer_ {
  /// See [Benutzer.id].
  static final id = obx.QueryIntegerProperty<Benutzer>(
    _entities[1].properties[0],
  );

  /// See [Benutzer.uid].
  static final uid = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[1],
  );

  /// See [Benutzer.partition].
  static final partition = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[2],
  );

  /// See [Benutzer.hlc].
  static final hlc = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[3],
  );

  /// See [Benutzer.knoten].
  static final knoten = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[4],
  );

  /// See [Benutzer.geloeschtAm].
  static final geloeschtAm = obx.QueryIntegerProperty<Benutzer>(
    _entities[1].properties[5],
  );

  /// See [Benutzer.schema].
  static final schema = obx.QueryIntegerProperty<Benutzer>(
    _entities[1].properties[6],
  );

  /// See [Benutzer.authId].
  static final authId = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[7],
  );

  /// See [Benutzer.salt].
  static final salt = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[8],
  );

  /// See [Benutzer.iterationen].
  static final iterationen = obx.QueryIntegerProperty<Benutzer>(
    _entities[1].properties[9],
  );

  /// See [Benutzer.storedKey].
  static final storedKey = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[10],
  );

  /// See [Benutzer.serverKey].
  static final serverKey = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[11],
  );

  /// See [Benutzer.rolle].
  static final rolle = obx.QueryStringProperty<Benutzer>(
    _entities[1].properties[12],
  );
}
